name: Push to Cloudformation stack

on: 
  workflow_dispatch:
  push:
    paths:
      - 'cf/**'
      - '.github/workflows/action-cf.yaml'

jobs:
  cf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: stack-${{ github.event.repository.name }}
          template: cf/${{ github.event.repository.name }}.yaml
          no-fail-on-empty-changeset: "1"
          disable-rollback: "1"
          parameter-overrides: >-
            paramRootDomain=lyc-handson-aws.com,
            paramSubdomain=www,
            paramTagName=${{ github.event.repository.name }}